@startuml

actor "Unregistered User" as UNU
participant "<<REST>>\nAPI" as API
participant "<<C4 Container>>\nSocialNetwork" as SN

activate UNU
UNU -> API: POST Player

activate API
API -> SN: Create(CreateUserAsPlayerDto)
deactivate API

activate SN
SN --> UNU : response JSON
deactivate SN

@enduml